project_name: kubeaudit
release:
  github:
    owner: MegaCloudContainer
    name: kubeaudit
  draft: true
  name_template: "{{.ProjectName}}-v{{.Version}}"
builds:
  - id: release
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - arm64
      - amd64
    goarm:
      - 6
      - 7
    main: ./cmd/main.go
    binary: kubeaudit
    ldflags:
      - -s -w -X github.com/MegaCloudContainer/kubeaudit/cmd.Version={{.Version}} -X github.com/MegaCloudContainer/kubeaudit/cmd.Commit={{.Commit}} -X github.com/MegaCloudContainer/kubeaudit/cmd.BuildDate={{.Date}}
    overrides:
      - goos: linux
        goarch: amd64
        goamd64: v1
        goarm: ""
        gomips: ""
        env:
          - CGO_ENABLED=0
          - GO111MODULE=on
dockers:
  - use: buildx
    ids:
      - release
    goos: linux
    goarch: amd64
    dockerfile: goreleaser.Dockerfile
    image_templates:
      - "ghcr.io/megacloudcontainer/kubeaudit:{{ .Tag }}-amd64"
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - "--build-arg"
      - "IMAGE_VERSION={{ .Tag }}"
  - use: buildx
    ids:
      - release
    goos: linux
    goarch: arm64
    dockerfile: goreleaser.Dockerfile
    image_templates:
      - "ghcr.io/megacloudcontainer/kubeaudit:{{ .Tag }}-arm64"
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - "--build-arg"
      - "IMAGE_VERSION={{ .Tag }}"
docker_manifests:
  - name_template: ghcr.io/megacloudcontainer/kubeaudit:{{ .Tag }}
    image_templates:
      - ghcr.io/megacloudcontainer/kubeaudit:{{ .Tag }}-amd64
      - ghcr.io/megacloudcontainer/kubeaudit:{{ .Tag }}-arm64
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - ^Merge

archives:
- format: tar.gz
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{.Arm }}{{ end }}'
  files:
  - licence*
  - LICENCE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
